import os

API_DIR = "kubernetes-api"
INDEX_PATH = os.path.join(API_DIR, "index.html")


def list_versions():
    return sorted(d for d in os.listdir(API_DIR) if os.path.isdir(os.path.join(API_DIR, d)) and not d.startswith("."))


def list_schema_files(version):
    version_dir = os.path.join(API_DIR, version)
    if not os.path.isdir(version_dir):
        return []
    return sorted(
        f for f in os.listdir(version_dir) if f.endswith(".json") and os.path.isfile(os.path.join(version_dir, f))
    )


def main():
    with open(INDEX_PATH, "w") as f:
        f.write("<!DOCTYPE html>\n<html>\n<head>\n")
        f.write("<meta charset='utf-8'>\n<title>Kubernetes JSON Schemas</title>\n")
        f.write("<style>body{font-family:sans-serif;} ul{margin-bottom:1.5em;} li{margin-bottom:0.2em;}</style>\n")
        f.write("</head>\n<body>\n")
        f.write("<h1>Kubernetes JSON Schemas</h1>\n")
        f.write(
            "<p>This page indexes all available Kubernetes JSON schemas by version. Click a version to see its schema files.</p>\n"
        )
        f.write("<ul>\n")
        for version in list_versions():
            f.write(f"  <li><details><summary><strong>{version}</strong></summary>\n")
            schema_files = list_schema_files(version)
            if schema_files:
                f.write("    <ul>\n")
                for schema in schema_files:
                    schema_path = f"{version}/{schema}"
                    f.write(f'      <li><a href="{schema_path}">{schema}</a></li>\n')
                f.write("    </ul>\n")
            else:
                f.write("    <em>No schemas found.</em>\n")
            f.write("  </details></li>\n")
        f.write("</ul>\n")
        f.write("<hr><small>Generated by <code>generate_index.py</code></small>\n")
        f.write("</body>\n</html>\n")


if __name__ == "__main__":
    main()
