import os

API_DIR = "kubernetes-api"
INDEX_PATH = os.path.join(API_DIR, "index.html")


def list_versions():
    versions = sorted(
        d for d in os.listdir(API_DIR) if os.path.isdir(os.path.join(API_DIR, d)) and not d.startswith(".")
    )
    versions.reverse()
    return versions


def list_schema_files(version):
    version_dir = os.path.join(API_DIR, version)
    if not os.path.isdir(version_dir):
        return []
    return sorted(
        f for f in os.listdir(version_dir) if f.endswith(".json") and os.path.isfile(os.path.join(version_dir, f))
    )


def main():
    with open(INDEX_PATH, "w") as f:
        f.write("""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Kubernetes JSON Schemas</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container my-5">
  <h1 class="mb-4">Kubernetes JSON Schemas</h1>
  <p class="lead">This page indexes all available Kubernetes JSON schemas by version. Click a version to see its schema files.</p>
  <div class="accordion" id="schemasAccordion">
""")
        for idx, version in enumerate(list_versions()):
            schema_files = list_schema_files(version)
            collapse_id = f"collapse{idx}"
            heading_id = f"heading{idx}"
            f.write(f'''  <div class="accordion-item">
    <h2 class="accordion-header" id="{heading_id}">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#{collapse_id}" aria-expanded="false" aria-controls="{collapse_id}">
        {version}
      </button>
    </h2>
    <div id="{collapse_id}" class="accordion-collapse collapse" aria-labelledby="{heading_id}" data-bs-parent="#schemasAccordion">
      <div class="accordion-body">
''')
            if schema_files:
                f.write('        <ul class="list-group list-group-flush">\n')
                for schema in schema_files:
                    schema_path = f"{version}/{schema}"
                    f.write(f'          <li class="list-group-item"><a href="{schema_path}">{schema}</a></li>\n')
                f.write("        </ul>\n")
            else:
                f.write("        <em>No schemas found.</em>\n")
            f.write("      </div>\n    </div>\n  </div>\n")
        f.write("""  </div>
  <hr class="mt-5">
  <small class="text-muted">Generated by <code>generate_index.py</code></small>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
""")


if __name__ == "__main__":
    main()
